### ISSUE TITLE
Split to Promptlist

### ISSUE THREAD

**Issue by dseditor** [VykosX/ControlFlowUtils#4]
Thank you for hard working.It's a powerful node tool with lots of functions.
But when I trying the node to split texts, the output can't directly using for prompt list.
Like cat//dog//puppy to [cat,dog,puppy] is really being splited ,but it gives only one line prompt.
How to create the multiline prompt to split cat//dog//puppy  and aux1 for // to 3 prompts or using list function?

**Comment by VykosX** [comment]
If you split a string, the output will be a list. You can access the individual results by forwarding the output to another String/List Operations node and use the GET_LINE operation, or you can use a Data Monitor, feed the output to aux, and obtain it by doing %aux%[0] (or whatever element index you wish) and setting the output of the Data Monitor node to FORMULA.

I hope this helps.
